# -*- coding: utf-8 -*-
"""Лабораторное занятие №1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KJI8J3jykivxgzpGGP-wCMzSG4dtAVVl
"""

#Colculiator
a = (input("your choce is *,/,-,+ : "))
b = int(input("first number : "))
c = int(input("the second number : "))

if a=="+":
  print(b+c);
elif a=="-":
  print(b-c);
elif a=="/":
  print(b/c)
elif a=="*":
  print(b*c);
else:
  print("Error!!!")

#2 Возвидение в квадрат 
a = 5
b = int(input("Введите число : "))
c = a + b
x = c**2
print("Сумма чисел = ", int(c))
print("Возведение суммы в квадрат = ",int(x))

#3
a = 15;
b = 10;
c = float(input());
x = (a+b)/c;
print("Результат программы!", int(x));

#4 Формула квадрата суммы (a*b)^2
a = int(input("Первое число : "))
b = int(input("Второе число : "))
c = (a**2 + 2*a*b + b**2)
print("Результат программы!", int(c))

#5 Формулы нахождения площади и периметра прямоугольника
a = int(input("Введите первое число : "))
b = int(input("Введите второе число : "))
c = int(input("Введите третье число : "))
#Находим периметр
p = (a+b+c)/2 
#Далее рассчитаем площадь
S = p ** (0.5)
print("Периметр!", int(p))
print("Площадь!", int(S))

#6 Решение неравенств
print("Решение неравенство ((a^3 + 14)/5)*b" )
a = int(input("Первое число : "))
b = int(input("Второе число : "))
c = ((a**3 + 14)/5)*b
print("Результат программы!", int(c))

#7

a = int(input("Введите первое число (a) : "))
c = a**2
print("a^2!",c)
b = int(input("Введите второе число (n): "))
x= c//b
print("Результат программы!", int(x))

#8
a = float(input("Первое число : "))
b = float(input("Второе число : "))
c = a//b
print(int(c))

a = int(input("Первое число : "))
b = int(input("Второе число : "))
c = a*b
print("Результат программы! ",c)

a = int(input("Первое число : "))
b = int(input("Второе число : "))
c = a%b
print("Результат программы! ",c)

#Задание 1

n = int(input("Введите число в секундах : "))
m = n/60
h = m/60
d= h/24
print("\nРезультат программы! ") 
print(round(m, 2) , "в минутах") 
print(round(h, 2) , "в часах") 
print(round(d, 2) , "в днях")

#Задание 2
n = int(input("Введите число : "))
x = n + n**2 + n**3
print("\nРезультат программы! " , x)