# -*- coding: utf-8 -*-
"""Лабораторное занятие №3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uR6viWmpNk2uaxYE58ISSXcRo6six5xX
"""

#1 - Месяца в году по порядке!
print("Месяца в году по порядке!!!")
n = int(input("Введите число (от 1 до 12) : "))
list1=["Январь","Февраль", "Март", "Июнь", "Июль", "Август", "Сентябрь", "Октябрь", "Ноябрь"]
if 0 < n < 12:  
  S = list1[n-1] 
  print("\nРезультат :", S)
else:
  print("Error!")

#2 - программа для фильтрации четных чисел
print("Программа для фильтрации четных чисел")
n = int(input("Введите число : "))
if (n%2)==0:
  print("ЧИСЛО ЯВЛЯЕТСЯ ЧЕТНЫМ !!! ")
elif n%2==1:
  print("ЧИСЛО НЕ ЯВЛЯЕТСЯ ЧЕТНЫМ !!!")
else:
  print("ERROR!!!!")

#3 - Дано число N
N = 54
if N>40:
  print("stonks")
elif N<40:
  print("not stonks")
else:
  print("ERROR")

#4 - високосный год

year = int(input())

def year1(a):
  return (a % 4 == 0) and (a % 100 != 0) or (a % 400 == 0)
print(year1(year))

#5 - Простое число
def IsPrime(n):
    d = 2
    while n % d != 0:
        d += 1
    return d == n

n =int(input("Введите число : "))
IsPrime(n)

#6 
import math 

a = float(input())
b = float(input())
c = (-138/2)**1.3;
d = (-69/28**5.1)*4;

cr = c.real
ci = c.imag

cm = -1 *(cr**2 + ci**2)**0.5 
dm = math.fabs((-69/28**5.1)*4)
print("до обмена :", "\n   a = ", a , "\n   b = ", b)

if a > b*3.6 or b >= cm  and b <= dm:
  a, b = b, a 
print("после обмена :", "\n   a = ", a , "\n   b = ", b)

#7 

number = [1,2,3,4,5]
number[0] = int(input("Введите 1-е число : "))
number[1] = int(input("Введите 2-е число : "))
number[2] = int(input("Введите 3-е число : "))
number[3] = int(input("Введите 4-е число : "))
number[4] = int(input("Введите 5-е число : "))
#Уникальные число
un = set(number)
if len(number) != len(un):
  print("Есть одинаковие числа")
else:
  print("Все числа уникальные")
#Количество четных и нечетных чисел
even_count, odd_count = 0, 0
for num in number:
    if num % 2 == 0:
        even_count += 1
    else:
        odd_count += 1
print("\nКоличество четных чисел: ", even_count)
print("Количество нечетных чисел: ", odd_count)
#Количество отрицательных чисел
neg_list = [n<0 for n in number]
print("Количество отрицательных чисел : ", neg_list.count(True))
#Количество чисел лежащих в промежутке [-256 ; 1024].
between_list = [n >= -256 and n <= 1024 for n in number]
print("Количество чисел в промежутке [-256 ; 1024]: ", between_list.count(True))

# Задание повышенной сложности 
a = int(input("Значения а :"))
b = int(input("Значенияя b :"))
c = int(input("Значения c :"))

s = a**2 + b**3
f = c + 3
e = s/f
S = e/4

print("\nРезультат :", S)

if S % 2 == 0:
  print(S, " является четным числом ")
else:
  print(S, "не является четным числом")